services:
  neo4j:
    image: neo4j:5.26.0
    container_name: nbp_projekat2
    volumes:
        - ./neo4j_data:/data
    environment:
        - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always